baseURL = "https://lkioi.me/"
languageCode = "en-us"
title = "Leonard Kioi"
theme = "hello-friend-ng"
[author]
  name = "Leonard Kioi"


[params]
homeSubtitle = "Software Craftsman | Maker"
description = "Portfolio site for Leonard Kioi Kinyanjui"
keywords = "portfolio,leonard,kioi,kinyanjui,software,software craftsman,engineer"
enableThemeToggle = true


[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/leonard-kioi-b6954841"


[[params.social]]
name = "github"
url  = "https://github.com/lenniezelk"


[[params.social]]
name = "dev"
url  = "https://dev.to/lenniezelk"


[[params.social]]
name = "twitter"
url  = "https://twitter.com/lk_kioi"


[[params.social]]
name = "email"
url  = "mailto:lenny.kinyanjui.lk@gmail.com"


[[params.social]]
name = "youtube"
url  = "https://www.youtube.com/channel/UC2yJRA9AaNxcJZjihIN8r0Q"


[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

[params.footer]
  trademark = true
  rss = true
  copyright = true
  author = true

  topText = []
  bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>",
          "Theme with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"]
